spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Priyanshu354/lovable-config-server
          default-label: main

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    config:
      enabled: false

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

---
spring:
  config:
    activate:
      on-profile: k8s
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Priyanshu354/lovable-config-server
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          default-label: main

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false